site_name: Data Visualization Guidelines


theme:
  name: material

  font:
    text: Colfax, sans-serif


nav:
  - index.md
  - Quick introduction: quick-intro.md
  - Guidelines:
      - Data viz principles: guidelines/principles.md
      - How to choose the right chart: guidelines/chart-selection.md
      - How to design a chart: guidelines/design-process.md
      - Accessibility: guidelines/accessibility.md
      - Interactivity: guidelines/interactivity.md
  - Style guide:
      - Colour palette: style-guide/colour-palette.md
      - Typography: style-guide/typography.md
      - Chart layout: style-guide/layout.md
  - Publishing checklist: publishing-checklist.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js