site_name: Data Visualization Guidelines

nav:
  - index.md
  - Quick introduction: quick-intro.md
  - Guidelines:
      - Data viz principles: guidelines/principles.md
      - How to choose the right chart: guidelines/chart-selection.md
      - How to design a chart: guidelines/design-process.md
      - Accessibility: guidelines/accessibility.md
      - Interactivity: guidelines/interactivity.md
  - Style guide:
      - Colour palette: style-guide/colour-palette.md
      - Typography: style-guide/typography.md
      - Chart layout: style-guide/layout.md
  - Publishing checklist: publishing-checklist.md